# Server Port
server.port=8081

spring.application.name=workflow-engine

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/workflow_engine
spring.datasource.username=engine_user
spring.datasource.password=secret_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Auto-DDL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Queue
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Enable Java 21 Virtual Threads for all incoming requests and I/O
spring.threads.virtual.enabled=true